# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pagoda}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tyler Flint"]
  s.date = %q{2011-04-28}
  s.default_executable = %q{pagoda}
  s.description = %q{client for interacting with the pagodagrid}
  s.email = %q{tyler@pagodagrid.com}
  s.executables = ["pagoda"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "bin/pagoda",
    "lib/pagoda.rb",
    "lib/pagoda/client.rb",
    "lib/pagoda/command.rb",
    "lib/pagoda/commands/app.rb",
    "lib/pagoda/commands/auth.rb",
    "lib/pagoda/commands/base.rb",
    "lib/pagoda/commands/help.rb",
    "lib/pagoda/commands/tunnel.rb",
    "lib/pagoda/helpers.rb",
    "lib/pagoda/tunnel_proxy.rb",
    "lib/pagoda/version.rb",
    "spec/base.rb",
    "spec/client_spec.rb",
    "spec/command_spec.rb",
    "spec/commands/auth_spec.rb"
  ]
  s.homepage = %q{http://pagodagrid.com/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{client for interacting with the pagodagrid}
  s.test_files = [
    "spec/base.rb",
    "spec/client_spec.rb",
    "spec/command_spec.rb",
    "spec/commands/auth_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<webmock>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_runtime_dependency(%q<iniparse>, [">= 0"])
      s.add_runtime_dependency(%q<crack>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<em-proxy>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<iniparse>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<em-proxy>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<iniparse>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<em-proxy>, [">= 0"])
  end
end

